components:
  sqlSource: { type: ref }
  rate: { type: stream, format: rate }
  sqlOnRate: { using: [rate], sql: "select *, value * 100 as bigValue from rate" }

sinks:
  showTable: { type: show }
  showRate:
    type: stream
    name: query
    format: console
    mode: APPEND
    trigger: { milliseconds: 1000 }

pipelines:
  batch: { component: sqlSource, sink: showTable }
  stream: { component: sqlOnRate, sink: showRate }
