CREATE TABLE SHARE_CONFIG (
    NAME varchar(1024) NOT NULL PRIMARY KEY
);

CREATE TABLE SCHEMA_CONFIG (
    SHARE_NAME varchar(1024) NOT NULL,
    NAME varchar(1024) NOT NULL,
    CONSTRAINT schemaConfigPrimaryKey PRIMARY KEY(SHARE_NAME, NAME),
    FOREIGN KEY (SHARE_NAME) REFERENCES SHARE_CONFIG(NAME)
);

CREATE TABLE TABLE_CONFIG (
    SHARE_NAME varchar(1024) NOT NULL,
    SCHEMA_NAME varchar(1024) NOT NULL,
    NAME varchar(1024) NOT NULL,
    LOCATION varchar(4096) NOT NULL,
    CONSTRAINT tableConfigPrimaryKey PRIMARY KEY(SHARE_NAME, SCHEMA_NAME, NAME),
    FOREIGN KEY (SHARE_NAME, SCHEMA_NAME) REFERENCES SCHEMA_CONFIG(SHARE_NAME, NAME)
);
