spring.flyway.locations: classpath:db/hsqldb/migration

---
spring.config.activate.on-profile: test
spring.datasource.url: jdbc:hsqldb:mem:devDb
spring.datasource.driver-class-name: org.hsqldb.jdbc.JDBCDriver