title: Spark Engine
description: Compose Apache Spark Datasets with ease.

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true
  show_sorted: false

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
