title: Spark Engine
description: Write a Spark execution plan using yaml
remote_theme: pmarsceill/just-the-docs
url: "https://www.spark-engine.com"

permalink: pretty
exclude:
  - "modules/"
  - README.md
  - CNAME

heading_anchors: true

search_enabled: true

aux_links:
  "GitHub":
    - "https://github.com/gabrielenizzoli/spark_engine"
  "Maven Central":
    - "https://search.maven.org/search?q=g:com.spark-engine"
aux_links_new_tab: true

nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2020-2021 me"

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
