components:

  config:
    type: inline
    data:
      - { wikipediaUrl: "http://dumps.wikimedia.your.org", fileDumpLocation: "${WIKIPEDIA_DOWNLOAD_LOCATION}" }
  wikipediaConfig:
    type: inline
    data:
      - { language: "${WIKIPEDIA_LANG}", date: "${WIKIPEDIA_DATE}" }

  wikipediaInfo:
    type: ref
  wikipediaDownload:
    type: ref

  xmlSource:
    type: batch
    format: xml
    options:
      path: ${WIKIPEDIA_DOWNLOAD_LOCATION}/lang=${WIKIPEDIA_LANG}/date=${WIKIPEDIA_DATE}
      rowTag: page
      samplingRatio: 0.05

  xml:
    sql: select * from xmlSource where ns = 0 and redirect._title is null

sinks:
  show: { type: show, truncate: 500 }

pipelines:
  downloadXml:
    order: 1
    layout: { component: wikipediaDownload, sink: show }
  readXml:
    order: 2
    layout: { component: xml, sink: show }